# On indique la version de docker compose
version: '3.3'

#Liste de l'ensemble de nos services (containers)
services: 

    # On déclare un container qui sera nommé php8
    php8: 
        image: php:8.1-apache
        ports:
            - 8080:80
        volumes:
            - ./src:/var/www/html

    # On déclare un container qui sera nommé php5
    php5: 
        image: php:5.6-apache
        ports:
            - 8081:80
        volumes:
            - ./src:/var/www/html